spring:
  liquibase:
    change-log: classpath:db/changelog/master.xml
    url: "jdbc:h2:mem:meetingrooms;MODE=Mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false;"

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:meetingrooms
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

